# Generated by Django 5.0.1 on 2024-01-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_leasing_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasing',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
