# Generated by Django 5.0.1 on 2024-01-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_leasing_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('more_info', models.TextField()),
                ('total_available_number', models.IntegerField()),
                ('is_still_in_stock', models.BooleanField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='car',
        ),
        migrations.RemoveField(
            model_name='leasing',
            name='car',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='leasing',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='transactions',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='leasing',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Leasing',
        ),
    ]
