# Generated by Django 5.0.1 on 2024-01-24 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_leasing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='name',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='more_info',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='year',
        ),
        migrations.RemoveField(
            model_name='leasing',
            name='car',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='car',
        ),
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('more_info', models.TextField()),
                ('total_available_number_of_car_features', models.IntegerField()),
                ('is_still_in_stock_of_car_features', models.BooleanField(null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.cars')),
            ],
        ),
        migrations.AddField(
            model_name='leasing',
            name='car_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.carfeature'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='car_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.carfeature'),
        ),
    ]
