# Generated by Django 5.0.1 on 2024-01-25 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_rename_name_cars_brand_remove_cars_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='car_feature',
        ),
        migrations.RemoveField(
            model_name='leasing',
            name='car_feature',
        ),
        migrations.AddField(
            model_name='cars',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='engine',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='more_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leasing',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.cars'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.cars'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='total_available_number',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='CarFeature',
        ),
    ]
