# Generated by Django 5.0.1 on 2024-01-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_cars_number_of_cars_in_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasing',
            name='mark_as_returned_from_lease',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
